# NumPy Arrays

## Creating numpy vector arrays from Python objects

In [4]:
import numpy as np

In [5]:
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

## Creating numpy matrix arrays from Python objects

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Creating Numpy arrays using built-in methods

In [8]:
# arange([start,]stop,[step,])
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
# zeros(dimension) - vector with 'dimension' columns
np.zeros(3)

array([0., 0., 0.])

In [11]:
# zeros((rows,columns)) - matrix with 'rows' rows and 'columns' columns
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# ones(dimension) - vector with 'dimensions' columns
np.ones(3)

array([1., 1., 1.])

In [13]:
# ones((rows,columns)) - matrix with 'rows' rows and 'columns' columns
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# linspace(start,stop,no_of_points) - returns an evenly spaced vector array of 'no_of_points' elements 
# between 'start' and 'stop'
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [16]:
# Creating an Identity matrix - identity matrix is always a square matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# np.random.rand(columns) - Creating a vector of random samples uniformly distributed over 0 to 1
np.random.rand(5)

array([0.22519304, 0.75779055, 0.27973348, 0.42295633, 0.71093902])

In [19]:
# np.random.rand(rows,columns) - Creating a matrix of random samples uniformly distributed over 0 to 1
np.random.rand(2,5)

array([[0.38885796, 0.96931768, 0.95277554, 0.33666339, 0.13528109],
       [0.80495672, 0.02345442, 0.53263654, 0.8454878 , 0.0066099 ]])

In [20]:
# np.random.randn(columns) - returns a vector with random samples not uniformly distributed over 0 to 1, but random
# samples from a standard normal distribution with centre around 0
np.random.randn(5)

array([-0.67268688,  0.0202659 , -0.20594139,  0.03211319, -2.00458755])

In [21]:
# np.random.randn(rows,columns) - returns a matrix with random samples not uniformly distributed over 0 to 1, but random
# samples from a standard normal distribution with centre around 0
np.random.randn(2,5)

array([[ 1.65267713, -0.88522341,  1.31108402,  0.24930578, -0.1284522 ],
       [ 0.43959444,  0.79139733,  0.50058891, -0.67816791,  1.55685844]])

In [22]:
# np.random.randint(low(inclusive),high(exclusive)) - returns a single random integer
np.random.randint(1,200)

86

In [23]:
# np.random.randint(low(inclusive),high(exclusive),num) - returns a vector of random integers, length = num
np.random.randint(1,200,10)

array([ 52, 123, 149, 124, 106, 167,   4,  65,  55,  84])

In [25]:
# reshape() - allows to change dimensions of the array i.e. return the array in a new shape
arr = np.arange(25)
print('Original: ')
print(arr)
print('Reshaped into a 5X5 matrix: ')
print(arr.reshape(5,5))

Original: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Reshaped into a 5X5 matrix: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


<b>NOTE: If vector cannot fill the resulting matrix completely, will throw an exception</b>

In [26]:
print(arr.reshape(5,10))

ValueError: cannot reshape array of size 25 into shape (5,10)

In [35]:
ranarr = np.random.randint(0,100,10)
ranarr

array([52, 72, 16, 45, 77, 91, 72, 98, 12, 60])

In [36]:
# Finding min and max from an array
print('Maximum number is: ' + str(ranarr.max()))
print('Minimum number is: ' + str(ranarr.min()))

Maximum number is: 98
Minimum number is: 12


In [37]:
# Finding indexes of min and max element in the array
print('Maximum number is located at: ' + str(ranarr.argmax()))
print('Minimum number is located at: ' + str(ranarr.argmin()))

Maximum number is located at: 7
Minimum number is located at: 8


In [38]:
# Getting the dimensions of an array using 'shape' ATTRIBUTE
print('Dimensions of arr: ' + str(arr.shape))
ranarr = ranarr.reshape(2,5)
print('Dimensions of ranarr: ' + str(ranarr.shape))

Dimensions of arr: (25,)
Dimensions of ranarr: (2, 5)


In [39]:
# Get data type of elements in the array
arr.dtype

dtype('int64')

In [40]:
# Getting a function reference for np.random.randint
from numpy.random import randint
randint(2,100,5)

array([51, 32, 61, 15, 14])